### PR TITLE
loot suggestions for supply crate

### PR DESCRIPTION
**Pull request by lokitheweaver**
If I have done this correctly, this should be my loot file (well, your loot file which I modified).  The current code meant few weapons - in 7 supply crates I only found one weapon.  Also some redundancy with food / tools - listed twice.  Finally changed the drop on the med supplies to 0,3 vs. 1,2.  Still the same overall average, but now there is a chance for none - obviously : )

### CODE REVIEW

**Comment by StompyNZ** [comment]
It appears you are trying to put the changed file into the root folder. Can you adjust it to be in the data/config folder so that a file compare can be done :)

this will also mean an easier job to merge it to the correct location should val decide he likes the changes

**Comment by lokitheweaver** [comment]
I actually (sort of) planned to do it that way - I had already sent him
some info on what I was trying to do and I thought that it would be
easier for him if I sent it as a stand alone file.  That way he could
just take "my" file and compare it to his original in notepad ++.  (If
that makes sense.)

Also, I had done the changes on my laptop, which did not (until today)
have GitHub installed.  So I would have needed to wait to make the
changes until I was able to come into my office, download / install
GitHub, etc.  By which time I would probably have forgotten half of what
I had discovered in playing the game.

But the "sort of" was a result of me trying to just drag / drop the file
I had changed into that "fork".  It worked out, but I could not figure
out how to replace the original loot.xml in the config folder, easily. 
Of course I may have just screwed everything up <LOL>

However, Valmar was able to open the file and see exactly what changes I
had recommended, so if I need to delete the file, I think I can do that.
 Right?

**Comment by StompyNZ** [comment]
That's all good Loki,  Was mostly thinking of long term processes to follow but as a workaround Val has been able to work with the method you used :)

**Comment by lokitheweaver** [comment]
Makes sense.  I am going to try the "normal" method, today - if I can
keep an internet connection for more than 2 minutes.  This library WiFi
is awful.

Dale Prey
Department of Fine Arts / Drama

> > > StompyNZ notifications@github.com 08/08/16 1:23 AM >>>
> > > That's all good Loki,  Was mostly thinking of long term processes to
> > > follow but as a workaround Val has been able to work with the method you
> > > used :)
> > >  —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/7days2mod/Valmod-Overhaul","title":"7days2mod/Valmod-Overhaul","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
in
GitHub","url":"https://github.com/7days2mod/Valmod-Overhaul"}},"updates":{"snippets":[{"icon":"PERSON","message":"@StompyNZ
in #1: That's all good Loki,  Was mostly thinking of long term processes
to follow but as a workaround Val has been able to work with the method
you used :)"}],"action":{"name":"View Pull
Request","url":"https://github.com/7days2mod/Valmod-Overhaul/pull/1#issuecomment-238144399"}}}
 Scanned for virus, malware, and spam by MEG75-1 appliance.

**Pull request closed without merging**
